listen              1935;
max_connections     10000;
daemon              off;

<<<<<<< HEAD
=======
# تحسين الاستقرار/الجتر
tcp_nodelay         on;
chunk_size          60000;

vhost __defaultVhost__ {
    http_hooks { enabled off; }

    hls {
        enabled         on;
        hls_path        /usr/local/srs/objs/nginx/html;
        hls_fragment    2;
        hls_window      30;
        hls_cleanup     on;
    }
}

>>>>>>> 6c7ce5680e5fd9af4b01dba38e650e77d7216fa2
http_server {
    enabled         on;
    listen          8080;
    dir             /usr/local/srs/objs/nginx/html;
}
<<<<<<< HEAD

# استخدم vhost "srs" لأننا سننشر على rtmp://srs:1935/live/xxx
vhost srs {
    hls {
        enabled         on;
        hls_path        /usr/local/srs/objs/nginx/html;
        hls_fragment    2;
        hls_window      30;
        hls_cleanup     off;
    }
}
=======
>>>>>>> 6c7ce5680e5fd9af4b01dba38e650e77d7216fa2
