server {
    listen 8081;
    server_name _;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location /live/ {
        alias /var/lib/streambox/hls/live/;
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Expose-Headers Content-Length;
        expires -1;
        autoindex on;
    }
}
